import { portfolioData } from '../../portfolio-data.js';

export const PROMPT_TEXT = 'Rishabh@portfolio ~ % ';
export const RESUME_URL = '/Rishabh_Trivedi_Resume.pdf';
export const EMAIL_HREF =
  'https://mail.google.com/mail/?view=cm&fs=1&to=rtrivedi.data@gmail.com&su=Connecting%20via%20portfolio';

export const THEMES = {
  hacker: {
    name: 'Hacker',
    light: {
      '--color-bg': '#0a0a0a',
      '--color-bg-secondary': '#111111',
      '--color-text': '#00FF00',
      '--color-text-secondary': '#00CC00',
      '--color-accent': '#00FF00',
      '--color-prompt': '#008800',
      '--color-border': '#004400',
      '--color-error': '#FF0000',
      '--network-rgb': '0, 255, 0',
    },
    dark: {
      '--color-bg': '#0a0a0a',
      '--color-bg-secondary': '#111111',
      '--color-text': '#00FF00',
      '--color-text-secondary': '#00CC00',
      '--color-accent': '#00FF00',
      '--color-prompt': '#008800',
      '--color-border': '#004400',
      '--color-error': '#FF0000',
      '--network-rgb': '0, 255, 0',
    }
  },
  nord: {
    name: 'Nord',
    light: {
      '--color-bg': '#ECEFF4',
      '--color-bg-secondary': '#E5E9F0',
      '--color-text': '#2E3440',
      '--color-text-secondary': '#4C566A',
      '--color-accent': '#5E81AC',
      '--color-prompt': '#81A1C1',
      '--color-border': '#D8DEE9',
      '--color-error': '#BF616A',
      '--network-rgb': '94, 129, 172',
    },
    dark: {
      '--color-bg': '#2E3440',
      '--color-bg-secondary': '#3B4252',
      '--color-text': '#ECEFF4',
      '--color-text-secondary': '#D8DEE9',
      '--color-accent': '#88C0D0',
      '--color-prompt': '#81A1C1',
      '--color-border': '#434C5E',
      '--color-error': '#BF616A',
      '--network-rgb': '136, 192, 208',
    }
  },
  dracula: {
    name: 'Dracula',
    light: {
      '--color-bg': '#282A36',
      '--color-bg-secondary': '#44475A',
      '--color-text': '#F8F8F2',
      '--color-text-secondary': '#6272A4',
      '--color-accent': '#FF79C6',
      '--color-prompt': '#8BE9FD',
      '--color-border': '#44475A',
      '--color-error': '#FF5555',
      '--network-rgb': '255, 121, 198',
    },
    dark: {
      '--color-bg': '#282A36',
      '--color-bg-secondary': '#44475A',
      '--color-text': '#F8F8F2',
      '--color-text-secondary': '#6272A4',
      '--color-accent': '#FF79C6',
      '--color-prompt': '#8BE9FD',
      '--color-border': '#44475A',
      '--color-error': '#FF5555',
      '--network-rgb': '255, 121, 198',
    }
  },
  retro: {
    name: 'Retro',
    light: {
      '--color-bg': '#2b1b05',
      '--color-bg-secondary': '#3a2507',
      '--color-text': '#FFB000',
      '--color-text-secondary': '#CC8C00',
      '--color-accent': '#FFD700',
      '--color-prompt': '#FF8C00',
      '--color-border': '#8B4500',
      '--color-error': '#FF4500',
      '--network-rgb': '255, 176, 0',
    },
    dark: {
      '--color-bg': '#2b1b05',
      '--color-bg-secondary': '#3a2507',
      '--color-text': '#FFB000',
      '--color-text-secondary': '#CC8C00',
      '--color-accent': '#FFD700',
      '--color-prompt': '#FF8C00',
      '--color-border': '#8B4500',
      '--color-error': '#FF4500',
      '--network-rgb': '255, 176, 0',
    }
  },
  matrix: {
    name: 'Matrix',
    light: {
      '--color-bg': '#000000',
      '--color-bg-secondary': '#051005',
      '--color-text': '#03A062',
      '--color-text-secondary': '#026639',
      '--color-accent': '#00FF41',
      '--color-prompt': '#008F11',
      '--color-border': '#005011',
      '--color-error': '#FF003C',
      '--network-rgb': '0, 255, 65',
    },
    dark: {
      '--color-bg': '#000000',
      '--color-bg-secondary': '#051005',
      '--color-text': '#03A062',
      '--color-text-secondary': '#026639',
      '--color-accent': '#00FF41',
      '--color-prompt': '#008F11',
      '--color-border': '#005011',
      '--color-error': '#FF003C',
      '--network-rgb': '0, 255, 65',
    }
  },
  synthwave: {
    name: 'Synthwave',
    light: {
      '--color-bg': '#2b213a',
      '--color-bg-secondary': '#3c2e4f',
      '--color-text': '#ff71ce',
      '--color-text-secondary': '#b967ff',
      '--color-accent': '#01cdfe',
      '--color-prompt': '#05ffa1',
      '--color-border': '#b967ff',
      '--color-error': '#fffb96',
      '--network-rgb': '1, 205, 254',
    },
    dark: {
      '--color-bg': '#2b213a',
      '--color-bg-secondary': '#3c2e4f',
      '--color-text': '#ff71ce',
      '--color-text-secondary': '#b967ff',
      '--color-accent': '#01cdfe',
      '--color-prompt': '#05ffa1',
      '--color-border': '#b967ff',
      '--color-error': '#fffb96',
      '--network-rgb': '1, 205, 254',
    }
  },
  default: {
    name: 'Default Theme',
    light: {
      '--color-bg': '#F6F4F0',
      '--color-bg-secondary': '#EDEAE4',
      '--color-text': '#2A2820',
      '--color-text-secondary': '#6A6860',
      '--color-accent': '#5A6050',
      '--color-prompt': '#8A8878',
      '--color-border': '#D0CEC8',
      '--color-error': '#A05040',
      '--network-rgb': '90, 96, 80',
    },
    dark: {
      '--color-bg': '#121212',
      '--color-bg-secondary': '#1e1e1e',
      '--color-text': '#e0e0e0',
      '--color-text-secondary': '#9e9e9e',
      '--color-accent': '#a0a694',
      '--color-prompt': '#d4d4cc',
      '--color-border': '#333333',
      '--color-error': '#cf6679',
      '--network-rgb': '160, 166, 148',
    }
  },
  tokyonight: {
    name: 'Tokyo Night',
    light: {
      '--color-bg': '#d5d6db',
      '--color-bg-secondary': '#cbccd1',
      '--color-text': '#343b58',
      '--color-text-secondary': '#6f799e',
      '--color-accent': '#33467c',
      '--color-prompt': '#8c4351',
      '--color-border': '#9699a3',
      '--color-error': '#c64343',
      '--network-rgb': '51, 70, 124',
    },
    dark: {
      '--color-bg': '#1a1b26',
      '--color-bg-secondary': '#16161e',
      '--color-text': '#c0caf5',
      '--color-text-secondary': '#a9b1d6',
      '--color-accent': '#7aa2f7',
      '--color-prompt': '#f7768e',
      '--color-border': '#3b4261',
      '--color-error': '#db4b4b',
      '--network-rgb': '122, 162, 247',
    }
  },
  gruvbox: {
    name: 'Gruvbox',
    light: {
      '--color-bg': '#fbf1c7',
      '--color-bg-secondary': '#ebdbb2',
      '--color-text': '#3c3836',
      '--color-text-secondary': '#504945',
      '--color-accent': '#b57614',
      '--color-prompt': '#9d0006',
      '--color-border': '#d5c4a1',
      '--color-error': '#cc241d',
      '--network-rgb': '181, 118, 20',
    },
    dark: {
      '--color-bg': '#282828',
      '--color-bg-secondary': '#1d2021',
      '--color-text': '#ebdbb2',
      '--color-text-secondary': '#a89984',
      '--color-accent': '#d79921',
      '--color-prompt': '#fb4934',
      '--color-border': '#504945',
      '--color-error': '#cc241d',
      '--network-rgb': '215, 153, 33',
    }
  },
  catppuccin: {
    name: 'Catppuccin Macchiato',
    light: {
      '--color-bg': '#eff1f5',
      '--color-bg-secondary': '#e6e9ef',
      '--color-text': '#4c4f69',
      '--color-text-secondary': '#6c6f85',
      '--color-accent': '#1e66f5',
      '--color-prompt': '#d20f39',
      '--color-border': '#bcc0cc',
      '--color-error': '#d20f39',
      '--network-rgb': '30, 102, 245',
    },
    dark: {
      '--color-bg': '#24273a',
      '--color-bg-secondary': '#1e2030',
      '--color-text': '#cad3f5',
      '--color-text-secondary': '#b8c0e0',
      '--color-accent': '#8aadf4',
      '--color-prompt': '#ed8796',
      '--color-border': '#494d64',
      '--color-error': '#ed8796',
      '--network-rgb': '138, 173, 244',
    }
  },
  rose_pine: {
    name: 'Rose Pine Moon',
    light: {
      '--color-bg': '#faf4ed',
      '--color-bg-secondary': '#f2e9e1',
      '--color-text': '#575279',
      '--color-text-secondary': '#797593',
      '--color-accent': '#907aa9',
      '--color-prompt': '#b4637a',
      '--color-border': '#dfdad9',
      '--color-error': '#b4637a',
      '--network-rgb': '144, 122, 169',
    },
    dark: {
      '--color-bg': '#232136',
      '--color-bg-secondary': '#2a273f',
      '--color-text': '#e0def4',
      '--color-text-secondary': '#908caa',
      '--color-accent': '#c4a7e7',
      '--color-prompt': '#eb6f92',
      '--color-border': '#44415a',
      '--color-error': '#eb6f92',
      '--network-rgb': '196, 167, 231',
    }
  },
  cyberdream: {
    name: 'Cyberdream',
    light: {
      '--color-bg': '#ffffff',
      '--color-bg-secondary': '#f1f1f1',
      '--color-text': '#16181a',
      '--color-text-secondary': '#5c6370',
      '--color-accent': '#5af78e',
      '--color-prompt': '#ff6e5e',
      '--color-border': '#d7d7d7',
      '--color-error': '#ff6e5e',
      '--network-rgb': '90, 247, 142',
    },
    dark: {
      '--color-bg': '#16181a',
      '--color-bg-secondary': '#1e2124',
      '--color-text': '#ffffff',
      '--color-text-secondary': '#7b8496',
      '--color-accent': '#5af78e',
      '--color-prompt': '#ff6e5e',
      '--color-border': '#3c4048',
      '--color-error': '#ff6e5e',
      '--network-rgb': '90, 247, 142',
    }
  },
  kanagawa: {
    name: 'Kanagawa Dragon',
    light: {
      '--color-bg': '#f2ecbc',
      '--color-bg-secondary': '#e5ddb0',
      '--color-text': '#545464',
      '--color-text-secondary': '#716e61',
      '--color-accent': '#957fb8',
      '--color-prompt': '#c84053',
      '--color-border': '#d5cea3',
      '--color-error': '#c84053',
      '--network-rgb': '149, 127, 184',
    },
    dark: {
      '--color-bg': '#181616',
      '--color-bg-secondary': '#12120f',
      '--color-text': '#c5c9c5',
      '--color-text-secondary': '#a6a69c',
      '--color-accent': '#8ba4b0',
      '--color-prompt': '#c4746e',
      '--color-border': '#282727',
      '--color-error': '#c4746e',
      '--network-rgb': '139, 164, 176',
    }
  },
  vesper: {
    name: 'Vesper',
    light: {
      '--color-bg': '#fafafa',
      '--color-bg-secondary': '#f0f0f0',
      '--color-text': '#101010',
      '--color-text-secondary': '#555555',
      '--color-accent': '#ffce51',
      '--color-prompt': '#ea4a5a',
      '--color-border': '#e0e0e0',
      '--color-error': '#ea4a5a',
      '--network-rgb': '255, 206, 81',
    },
    dark: {
      '--color-bg': '#101010',
      '--color-bg-secondary': '#161616',
      '--color-text': '#a0a0a0',
      '--color-text-secondary': '#606060',
      '--color-accent': '#ffce51',
      '--color-prompt': '#ea4a5a',
      '--color-border': '#252525',
      '--color-error': '#ea4a5a',
      '--network-rgb': '255, 206, 81',
    }
  },
  challenger_deep: {
    name: 'Challenger Deep',
    light: {
      '--color-bg': '#e3eaf0',
      '--color-bg-secondary': '#d7dce2',
      '--color-text': '#1e1e2e',
      '--color-text-secondary': '#56566d',
      '--color-accent': '#91ddff',
      '--color-prompt': '#ff5458',
      '--color-border': '#c5cbd2',
      '--color-error': '#ff5458',
      '--network-rgb': '145, 221, 255',
    },
    dark: {
      '--color-bg': '#1e1e2e',
      '--color-bg-secondary': '#1b1b29',
      '--color-text': '#cbe3e7',
      '--color-text-secondary': '#a6b3cc',
      '--color-accent': '#91ddff',
      '--color-prompt': '#ff5458',
      '--color-border': '#2d2d45',
      '--color-error': '#ff5458',
      '--network-rgb': '145, 221, 255',
    }
  },
  night_owl: {
    name: 'Night Owl',
    light: {
      '--color-bg': '#f0f8ff',
      '--color-bg-secondary': '#e3eff7',
      '--color-text': '#011627',
      '--color-text-secondary': '#403f53',
      '--color-accent': '#82aaff',
      '--color-prompt': '#ef5350',
      '--color-border': '#d3e2ef',
      '--color-error': '#ef5350',
      '--network-rgb': '130, 170, 255',
    },
    dark: {
      '--color-bg': '#011627',
      '--color-bg-secondary': '#01101a',
      '--color-text': '#d6deeb',
      '--color-text-secondary': '#637777',
      '--color-accent': '#82aaff',
      '--color-prompt': '#ef5350',
      '--color-border': '#0b2942',
      '--color-error': '#ef5350',
      '--network-rgb': '130, 170, 255',
    }
  },
  oxocarbon: {
    name: 'Oxocarbon Dark',
    light: {
      '--color-bg': '#f2f4f8',
      '--color-bg-secondary': '#e5e7eb',
      '--color-text': '#161616',
      '--color-text-secondary': '#525252',
      '--color-accent': '#08bdba',
      '--color-prompt': '#ff7eb6',
      '--color-border': '#d0d4d9',
      '--color-error': '#ff7eb6',
      '--network-rgb': '8, 189, 186',
    },
    dark: {
      '--color-bg': '#161616',
      '--color-bg-secondary': '#262626',
      '--color-text': '#f2f4f8',
      '--color-text-secondary': '#8d8d8d',
      '--color-accent': '#08bdba',
      '--color-prompt': '#ff7eb6',
      '--color-border': '#393939',
      '--color-error': '#ff7eb6',
      '--network-rgb': '8, 189, 186',
    }
  },
  material_ocean: {
    name: 'Material Ocean',
    light: {
      '--color-bg': '#f5f6f8',
      '--color-bg-secondary': '#eaebed',
      '--color-text': '#0f111a',
      '--color-text-secondary': '#546e7a',
      '--color-accent': '#82aaff',
      '--color-prompt': '#f07178',
      '--color-border': '#cfd4d8',
      '--color-error': '#f07178',
      '--network-rgb': '130, 170, 255',
    },
    dark: {
      '--color-bg': '#0f111a',
      '--color-bg-secondary': '#090a0f',
      '--color-text': '#8f93a2',
      '--color-text-secondary': '#4b5263',
      '--color-accent': '#82aaff',
      '--color-prompt': '#f07178',
      '--color-border': '#1d212f',
      '--color-error': '#f07178',
      '--network-rgb': '130, 170, 255',
    }
  },
  palenight: {
    name: 'Palenight',
    light: {
      '--color-bg': '#ffffff',
      '--color-bg-secondary': '#f0f0f0',
      '--color-text': '#292d3e',
      '--color-text-secondary': '#676e95',
      '--color-accent': '#82aaff',
      '--color-prompt': '#f07178',
      '--color-border': '#e0e0e0',
      '--color-error': '#f07178',
      '--network-rgb': '130, 170, 255',
    },
    dark: {
      '--color-bg': '#292d3e',
      '--color-bg-secondary': '#1e202e',
      '--color-text': '#a6accd',
      '--color-text-secondary': '#676e95',
      '--color-accent': '#82aaff',
      '--color-prompt': '#f07178',
      '--color-border': '#3c4059',
      '--color-error': '#f07178',
      '--network-rgb': '130, 170, 255',
    }
  }
};

export const DEFAULT_THEME = 'default';

export const COMMAND_NAMES = [
  'availability',
  'download resume',
  'sys --alloc',
  'sys --threads',
  'sys --shell',
  'sys --status',
  'sys --help',
  'diagnostics',
  'theme --list',
  'help',
  'man',
  'about',
  'log',
  'education',
  'experience',
  'projects',
  ...portfolioData.projects.map((project) => `projects ${project.slug}`),
  'skills',
  'resume',
  'contact',
  'creator',
  'sudo hire',
  'decisions',
  'stats',
  'whoami',
  'timeline',
  'ls',
  'pwd',
  'cd',
  'cat',
  'echo',
  'date',
  'all',
  'clear',
  'ping',
  'ifconfig',
  'ip a',
  'netstat',
  'traceroute',
];

export const COMMAND_GROUPS = [
  {
    title: 'About this site',
    commands: ['diagnostics', 'theme --list', 'creator'],
  },
  {
    title: 'Portfolio',
    commands: ['about', 'experience', 'education', 'projects', 'skills'],
  },
  {
    title: 'Systems demos',
    commands: ['sys --alloc', 'sys --threads', 'sys --shell', 'sys --status'],
  },
  {
    title: 'Networking',
    commands: ['ping', 'ifconfig', 'ip a', 'netstat', 'traceroute'],
  },
  {
    title: 'Contact & hiring',
    commands: ['contact', 'availability', 'resume', 'download resume', 'sudo hire'],
  },
  {
    title: 'Terminal',
    commands: ['help', 'man', 'log', 'all', 'clear'],
  },
];

export const COMMAND_MANUALS = {
  availability: {
    summary: 'Show current job search availability.',
    usage: 'availability',
    description: 'Shows open role types, preferred location setup, and immediate start status.',
  },
  'download resume': {
    summary: 'Download the resume PDF without leaving the terminal.',
    usage: 'download resume',
    description: 'Triggers a browser download for the latest resume and prints the direct file link.',
  },
  sys: {
    summary: 'List available sys namespace commands.',
    usage: 'sys --help',
    description: 'Shows the supported systems-portfolio subcommands and what each one demonstrates. Equivalent to sys --help.',
  },
  'sys --alloc': {
    summary: 'Preview allocator benchmark work.',
    usage: 'sys --alloc',
    description: 'Reserved sys namespace entry for the custom allocator benchmark view.',
  },
  'sys --threads': {
    summary: 'Preview threading and concurrency work.',
    usage: 'sys --threads',
    description: 'Reserved sys namespace entry for the threads and synchronization demo view.',
  },
  'sys --shell': {
    summary: 'Preview the shell demo workspace.',
    usage: 'sys --shell',
    description: 'Reserved sys namespace entry for the mini shell demo linked against the allocator project.',
  },
  'sys --status': {
    summary: 'Print live terminal diagnostics.',
    usage: 'sys --status',
    description: 'Prints the same one-shot diagnostics block as diagnostics, using live browser and session stats.',
  },
  'sys --help': {
    summary: 'List available sys namespace commands.',
    usage: 'sys --help',
    description: 'Shows the supported systems-portfolio subcommands and what each one demonstrates.',
  },
  diagnostics: {
    summary: 'Print live terminal diagnostics.',
    usage: 'diagnostics',
    description: 'Prints a one-shot health block with actual runtime stats from the current browser session.',
  },
  'theme --list': {
    summary: 'Show all available colour themes.',
    usage: 'theme --list',
    description: 'Lists every built-in theme by name. Use theme [name] to apply one. Your choice is remembered.',
  },
  help: {
    summary: 'Show available commands and usage guidance.',
    usage: 'help',
    description:
      'Lists the built-in terminal commands and reminds visitors that they can also ask natural-language questions.',
  },
  man: {
    summary: 'Display a manual page for a built-in command.',
    usage: 'man [command]',
    description:
      'Opens a Unix-style manual page with the command summary, usage, and behavior. Example: man projects',
  },
  about: {
    summary: 'Print the personal background section.',
    usage: 'about',
    description: 'Shows Rishabh Trivedi’s story, interests, and current direction.',
  },
  log: {
    summary: 'View career and life system log.',
    usage: 'log',
    description: 'Prints a chronological deployment log of career events, milestones, and active background processes.',
  },
  education: {
    summary: 'Show academic history.',
    usage: 'education',
    description: 'Prints degree, school, graduation, and GPA details.',
  },
  experience: {
    summary: 'Show professional experience.',
    usage: 'experience',
    description: 'Lists internships, teaching roles, and day-to-day impact across positions.',
  },
  projects: {
    summary: 'List all projects with descriptions and links.',
    usage: 'projects [name]',
    description:
      'Without an argument, shows Featured Projects and Other Work with one-line descriptions and links. ' +
      'With a name, shows the full deep-dive: stack, pipeline, GitHub, and live demo where available. ' +
      `Names: ${portfolioData.projects.map((project) => project.slug).join(', ')}`,
  },
  skills: {
    summary: 'Show technical skill categories.',
    usage: 'skills',
    description: 'Displays grouped skills across languages, frameworks, tools, and domains.',
  },
  languages: {
    summary: 'Show spoken languages.',
    usage: 'languages',
    description: 'Prints language fluency information.',
  },
  certifications: {
    summary: 'Show certifications and credentials.',
    usage: 'certifications',
    description: 'Lists certifications with issuers and links where available.',
  },
  hackathons: {
    summary: 'Show hackathon projects.',
    usage: 'hackathons',
    description: 'Lists hackathons participated in, what was built, team size, and links.',
  },
  talks: {
    summary: 'Show talks and presentations.',
    usage: 'talks',
    description: 'Prints speaking engagements, lecture topics, and venues.',
  },
  leadership: {
    summary: 'Show leadership roles.',
    usage: 'leadership',
    description: 'Lists organizations, roles, and measurable leadership contributions.',
  },
  resume: {
    summary: 'Open the latest resume.',
    usage: 'resume',
    description: 'Shows a direct link to the current hosted PDF resume.',
  },
  contact: {
    summary: 'Show contact links.',
    usage: 'contact',
    description: 'Prints email, LinkedIn, and GitHub contact paths.',
  },
  creator: {
    summary: 'Show the signature ASCII creator card.',
    usage: 'creator',
    description: 'Renders the portfolio’s ASCII art easter egg.',
  },
  'sudo hire': {
    summary: 'Print the strongest quick case for hiring Rishabh.',
    usage: 'sudo hire',
    description: 'Outputs a concise hiring pitch with resume and scheduling links.',
  },
  decisions: {
    summary: 'Show real engineering tradeoffs behind the work.',
    usage: 'decisions',
    description:
      'Six concrete implementation decisions with alternatives considered and tradeoffs made — WASM constraints, Airflow task design, parallel agent execution, caching strategy.',
  },
  stats: {
    summary: 'Show developer statistics.',
    usage: 'stats',
    description: 'Outputs language proficiency in an interactive progress bar style.',
  },
  whoami: {
    summary: 'Shows a short introduction.',
    usage: 'whoami',
    description: 'Prints a brief overview of my identity, education, and interests.',
  },
  timeline: {
    summary: 'Display my educational and professional timeline.',
    usage: 'timeline',
    description: 'Outputs a chronological ordering of my key experiences and academic milestones.',
  },
  all: {
    summary: 'Print all portfolio sections in sequence.',
    usage: 'all',
    description: 'Outputs the full portfolio content as one long terminal session.',
  },
  clear: {
    summary: 'Clear the terminal output and reboot the shell.',
    usage: 'clear',
    description: 'Resets terminal history and restarts the boot message.',
  },
};
